### ISSUE TITLE
Create an easy step by step guide for non Techs how to setup and run an IOTA Node

### ISSUE THREAD

**Issue by Phyloiota** [iota-community/X-Team_IOTA_Simplify#15]
# Goal Title
**Priority: (B)**
We can provide an extended explanation of how to setup a node, so members with only a basic computer knowledge could participate in supporting the network. This should go beyond the already existing guides and docs and focus on the surrounding requirements. (Setup an VPN, Basic console commands to start and activate the system, basic troubleshooting) and explain the confusing glossary. This will be a helpdocument / (video maybe) to use a simple droplet / one line command installation and should explain the still needed manual tasks (VPS porting, execute linux commandline, accessing the dashboard, etc)

## Key results
1. - [ ] One
1. - [ ] Two
1. - [ ] Three

# Team
IOTA Simplify- IOTA Experience Team (Phylo#2233)

### X-Team members
@githubusername - Name Surname - thisis@myema.il 

### IOTA Foundation member
@githubusername - Name Surname - thisis@iota.org

# Additional Information
* link to project
* link to documentation
* link to repository
* link

# Governance
Please use the following emoji reactions in this post to indicate:
:+1: - Participating
:heavy_plus_sign: - Add my vote

**Comment by Phyloiota** [comment]
Just an update - basic layout of presentation is done and tested a few times already - gonna do a run with Roy soon and some recordings, goal is to have a installation party on Discord for interested people to go through the process together

**Comment by Roy-export** [comment]
Hi Phylo! looking forwards to getting this done!  I suggest we do several videos:
1) Pre install - how do you get a VPS and security
2) Install - steps to install
3) How to modify the config.json
4) Maintenance - How to update

**Comment by Roy-export** [comment]
The video has been uploaded to Shared drive - just waiting for voice overs

**Comment by Phyloiota** [comment]
Thats finished for now
