### ISSUE TITLE
Create a Tech - FAQ 

### ISSUE THREAD

**Issue by Phyloiota** [iota-community/X-Team_IOTA_Simplify#4]
We try to collect all kind of possible questions related to the Tech and Science behind IOTA. Try to explain in more simple words the conversations that happen in "Tanglemath" Also should be usable to create an "Anti FUD" Guide to conquer common misinterpretations or false statements about IOTA in the general crypto space.
Use the linked spreadsheet
[https://docs.google.com/spreadsheets/d/1w7b28pLomZeCTYYd67ffGkxE5qCyOt4_tH0HO8wp3Ws/edit?usp=sharing](url)
 as a collection of questions and possible answers. We hope especially that members of the IF could try to give simple answers to those questions or could review our statements to validate them

**Comment by antonionardella** [comment]
Hello @Phyloiota, I have added a FAQ section in the GitHub discussions here:
https://github.com/iota-community/X-Team_IOTA_Simplify/discussions/categories/q-a

Let us add the questions here and invite IOTA community members to add their questions
